---
title: "test"
author: "Đinh Quang Dũng"
date: "2024-03-04"
output: html_document
---




set.seed(1)
# chia bộ dữ liệu thành test và train
sample = sample(c(TRUE, FALSE), nrow(cars), replace = TRUE, prob = c(0.65, 0.35) );

train = cars[sample,]
test = cars[!sample,]
lm.fit_training = lm(train$dist ~ train$speed)
lm.fit_training
##Phương trình hồi quy tuyến tính là: Y = -16.609 + 3.843 * X


##Kiểm định xem a0 có thực sự khác 0 hay không?
summary(lm.fit_training)
##H0: a0 = 0 >< H1: a0 != 0
##p-value = 0.0271 < 0.05 -> Bác bỏ H0 -> a0 khác 0
##H1: a1 = 0 >< H1: a1 !=
##p-value < 0.05 -> Bác bỏ H0 -> a1 khác 0


## khoảng tin cậy với độ tin cậy 95% cho hai hệ số a0, a1
confint(lm.fit_training)
##Khoảng tin cậy 95% cho a0: (-31.191826; -2.026813)
##Khoảng tin cậy 95% cho a1: (2.928665; 4.757896)


##Kiểm định xem phần dư của lm.fit_training có tuân theo phân phối chuẩn với giá trị trung bình bằng 0 hay không!
##H0: Phần dư tuân theo phân phối chuẩn >< H1: ngược lại
shapiro.test(lm.fit_training$residuals)
## p-value = 0.3134 > 0.05 -> Chấp nhận H0 -> phần dư tuân theo phân phối chuẩn 
##H0: E(Phần dư) = 0 >< H1: E(Phần dư) != 0
t.test(lm.fit_training$residuals)
## p-value = 1 > 0.05 -> Chấp nhận H0 -> phần dư tuân theo phân phối chuẩn với giá trị trung bình bằng 0


##Đánh giá trên bộ dữ liệu testing 
y = test$dist
TSS = sum((y - mean(y))^2)
y_h = -16.609 + 3.843 * test$speed
RSS = sum((y - y_h)^2)
R2 = 1 - RSS/TSS
R2